blank_issues_enabled: false
contact_links:
    - name: Tallycord Support Server
      url: https://discord.gg/D9uwnFnqmd
      about: If you need help regarding Tallycord, please join our support server!
    - name: Tallycord Installer
      url: https://github.com/Tallycord/Installer
      about: You can find the Tallycord Installer here
