name: Build
on:
    push:
        tags:
            - v*

env:
    FORCE_COLOR: true

jobs:
    Build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v3 # Install pnpm using packageManager key in package.json

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build web
              run: pnpm buildWebStandalone

            - name: Build
              run: pnpm build --standalone

            # - name: Generate plugin list
            #   run: pnpm generatePluginJson dist/plugins.json dist/plugin-readmes.json

            - name: Upload each file in dist as separate artifact
              shell: bash
              run: |
                  for file in dist/*; do
                    name=$(basename "$file")
                    echo "Uploading $file as $name"
                    gh run upload-artifact "$name" "$file"
                  done
              env:
                  GH_TOKEN: ${{ github.token }}
